name: "Continuous Integration"

on: [push, pull_request]

jobs:
  build:
    name: "Test project"
    runs-on: ubuntu-latest
    envs:
      MYVAR: amazement
    steps:
    - uses: actions/checkout@v2.0.0

    - name: "Git Version"
      run: "git --version"
